# Generated by Django 5.2 on 2026-04-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posted_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
